### ISSUE TITLE
残機能実装スケジュール策定

### ISSUE THREAD

**Issue by ys1227** [ys1227/link_discord#120]
* スケジュールについて
 - [x] ユーザー画面追加
 - [x] ゲストログイン機能を追加
 - [ ] rubocop修正 1/28〆
 - [ ] フォロー・フォロワー機能追加　1/28〆
 - [ ] 投稿時のアルゴリズムを実装  1/29〆

お疲れ様です。提出が遅くなってしまい申し訳ございません。
残りのスケジュールについて上記のような日程で進めていこうと考えています。
Action Cableについての実装ですが、バトランでレビューをいただいた時に、チャット機能はDiscordにあるため
特に必要ないかもしれないとのレビューをいただき、その通りだと感じたため、本リリースには含めないでおこうと思っております。
ご確認お願いいたします。

**Comment by tmtkzk0823** [comment]
確認させていただきました！

本リリースまでもう少しなので頑張っていきましょう！

**Comment by ys1227** [comment]
本リリース確認依頼
 - [x] ユーザー画面追加
 - [x] ゲストログイン機能を追加
 - [x] rubocop修正 1/28〆
 - [x] ActionCableによるチャット機能追加


お疲れ様です。
本リリース予定の機能を実装したしましたのでご確認お願い致します。🙇🏻‍♀️

rubocopの実施結果
```
bundle exec rubocop
Inspecting 92 files
............................................................................................

92 files inspected, no offenses detected

```

当初はActionCableによるチャット機能を実装しない予定だったのですが、
自身が使用していて集合時間決定後に急に参加できなくなった時などにチャット機能を使用して
参加メンバーに対して時間帯の調整などを連絡ができたらいいなと思ったため実装させていただきました。

また、投稿時のアルゴリズムを設定という機能なのですが、当初はフォローしていている順番に投稿一覧画面を並べる、という機能を予定しておりました。
しかし締め切り期限で並んでいる方が見やすいと感じたため機能を省かせていただきたいです。🙇🏻‍♀️
またフォローフォロワー機能なのですが、上記のアルゴリズム実装のために実装を予定しておりましたが、
実装をキャンセルしたことにより特にフォローフォロワー機能を用いて何かをする予定がないため、実装をキャンセルさせていただきたいです。🙇🏻‍♀️

色々と変更してしまいすいません。🙇🏻‍♀️
よろしくお願い致します。🙇🏻‍♀️

**Comment by tmtkzk0823** [comment]
ご連絡ありがとうございますー！
実装お疲れ様です！
> また、投稿時のアルゴリズムを設定という機能なのですが、当初はフォローしていている順番に投稿一覧画面を並べる、という機能を予定しておりました。
しかし締め切り期限で並んでいる方が見やすいと感じたため機能を省かせていただきたいです。🙇🏻‍♀️
またフォローフォロワー機能なのですが、上記のアルゴリズム実装のために実装を予定しておりましたが、
実装をキャンセルしたことにより特にフォローフォロワー機能を用いて何かをする予定がないため、実装をキャンセルさせていただきたいです。🙇🏻‍♀️

上記承知しました！
フォローフォロワー機能、アルゴリズムの代わりとしてActionCableを使ったチャット機能を実装しているので大丈夫だと思います。

アプリの方は大丈夫でしたので、コードを確認して気になった箇所をコメントさせていただきますね！
- `app/controllers/questions_controller.rb`の61行目等、コメントアウトで記載してあるコードが何箇所がありそうなので、使用しないコードは削除しておいたほうが良さそうに思いました！
- `@hoge = Hoge.find(params: [:id])`等の記述はprivateに切り出して共通化し、コードをスッキリ見せてあげると良さそうです！

また、就活を進めるに当たってREADMEの修正もしておきましょう！
- `実装を予定している機能`の項目と、`MVP`、`本リリース`を削除していただき、「機能一覧」のような項目に変更していただく（「機能一覧」は例ですので、他の方のREADME等を参考にしてもいいと思います！）
- アプリの画像等を使用して、「何ができるアプリなのか」をREADMEからわかるようにする。良さそう[記事](https://zenn.dev/bloomer/articles/3f73f7d02e5a63)があったので共有させていただきますね！
（山本さんのアプリケーションはDiscordのRUNTEQサーバーを対象としているので、第三者がREADMEを読んだだけでアプリの使用イメージが想像できるくらい詳細に作成してもいいと思います！）

以上です！
上記、コメントを残させていただきましたが、アプリケーションは完成しているので、**本リリースして大丈夫**だと思います！
リリースをしたらREADMEの修正を優先に行いましょう！
コードの修正はその後で大丈夫かと🙌

就活頑張ってください！
