### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by ys1227** [ys1227/link_discord#84]
## 各種情報
サービス名 : Link_Disco
サービスURL : https://link-disco.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- MVPリリース

1.  ユーザー新規登録機能
2. ログイン機能
3. 投稿機能(index/show/create/update/edit/destroy/new)
4. マッチング機能
5. フォロー/ フォロワー機能
6. カテゴリ設定機能
7. カテゴリ検索機能
8. LINE通知機能でマッチングが成立した際にLINEで通知が届くように設定。
9. 利用規約
10. プライバシーポリシー

## README時から追加した機能
* SidekiqとRedisを導入して、APIのリクエストのレートリミット対策としてDiscordのHTTPAPIのリクエストの間隔を調整しました。
* ９番でLINEで通知としていますが、DiscordログインのためDiscordのDMでの通知に変更しました。

フォローフォロワー機能なのですがメインの予約機能とはあまり関係がないため本リリースで追加とさせていただくことは可能でしょうか。

## サービスイメージがわかるようなスクリーンショット等

[![Image from Gyazo](https://i.gyazo.com/3ca6ee90f1b3ea0497c2c7e99166d3ea.png)](https://gyazo.com/3ca6ee90f1b3ea0497c2c7e99166d3ea)

[![Image from Gyazo](https://i.gyazo.com/65c364e47979e4383fb50d8e5de24bf0.png)](https://gyazo.com/65c364e47979e4383fb50d8e5de24bf0)

Sidekiq-schedulerで締め切り時間になったらQuestionモデルのStateカラムを変更するように定期Jobを実行しています。
[![Image from Gyazo](https://i.gyazo.com/0263d1789bdf689f578eb71ec8fe70a9.jpg)](https://gyazo.com/0263d1789bdf689f578eb71ec8fe70a9)

上記の定期Jobが実行されたらDiscordにDMを送信するHTTPリクエストを送信するJobを呼び出すように実装しました。
Sidekiqでエンキューされてからデキューするまでの時間を設定してSidekiqのスレッドを１で設定することで
サーバーに対して一気にリクエストを送信しないようにリクエストの間隔を調整しました。
[![Image from Gyazo](https://i.gyazo.com/049575aae22b820dbeb1efe40d686ba6.jpg)](https://gyazo.com/049575aae22b820dbeb1efe40d686ba6)

よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
MVP機能の実装ができているかを確認しようとしましたが、ページ表示・ページ遷移に時間がだいぶかかってしまう状態です...

挙動確認ができるようにrenderの有料化やherokuでのデプロイなど、他者がサービスを触れられる状態での提出をお願いいたします。

https://github.com/ys1227/link_discord/assets/61481161/8aa13976-8d7d-47db-b40a-07cf4d36f66b

**Comment by ys1227** [comment]
@Tsuchiya2講師レビューありがとうございます。

申し訳ございません。
Renderでサーバーを有料化し、デプロイし直して修正いたしました。
よろしくお願いいたします。

**Comment by ys1227** [comment]
@murata0705講師レビューありがとうございます。

> また、パスワードリセットは Discord アカウントでログインするのでチェック不要ですかね？

はい！申し訳ございません。消し忘れていました。

> こちらエラーが出るので確認お願いします！

修正いたしました。

よろしくお願いいたします。

**Comment by ys1227** [comment]
mutara0705講師レビューありがとうございます。
 
* マッチング機能
質問投稿後、自分がDiscordに集まりたい時間の中から、他のユーザーに対して投票を募集する募集時間を第一希望から最大で第三希望まで登録していただくことができます。
募集時間のうち一番早い時間の12時間前に投票締め切り時間が設定されます。
募集時間の投稿完了後、他のユーザーが設定した募集時間に対して締め切り時間まで投票ができるようになります。
例）ユーザーAが投稿した場合

カテゴリー : 質問
内容:　課題の内容がわかりません。
第一希望 : 12/16 21.00-
第二希望 : 12/17 21.00-
第三希望 : 12/18 21.00-

上記の内容を設定すると投稿時に締め切り時間が12/16 AM09:00に投票締め切り時間が設定されます。
その時間まで投票を募集することができ、一番投票人数が多かった日にちでDiscordに集まる日にちが決定します。
日にちが決定するとDiscrodのDMで通知をします。

*  LINE通知機能でマッチングが成立した際にLINEで通知が届くように設定。
DiscordログインにしたためLINEではなくDiscrod DMでの通知に変更させていただきました。
最初のプルリクスト時に反映し忘れていました。申し訳ございません。
上記のマッチング機能を使って投票締め切り時間が到来したら、
DiscordのDMで集合時間を通知させていただきます。
[![Image from Gyazo](https://i.gyazo.com/8acfdc3470f856f20a01fce4d0c55a2c.jpg)](https://gyazo.com/8acfdc3470f856f20a01fce4d0c55a2c)


 * カテゴリ設定機能
[![Image from Gyazo](https://i.gyazo.com/26987c552622099ef8798922f8e9b46c.png)](https://gyazo.com/26987c552622099ef8798922f8e9b46c)

質問設定時以下の５つのカテゴリを選択することができます。
* 質問
* 雑談
* 就活
* アプリ
* その他


 * カテゴリ検索機能
 以下の画面から投稿に設定されているカテゴリを検索することができます。
自分が集まりたいカテゴリに対して検索をかけることができます。
[![Image from Gyazo](https://i.gyazo.com/99957f9cf5247aaa42a1e5c191efbec8.gif)](https://gyazo.com/99957f9cf5247aaa42a1e5c191efbec8)

* フォローフォロワー機能
この機能を使って、投稿の一覧表示を自分がフォローしているユーザーの順番に並べ替える機能を本リリースで予定していました。
MVPリリース時にフォローフォロワー機能だけつけていてもユーザーを混乱させてしまうだけのような気がしたので、本リリース後の実装とさせていただくことは可能でしょうか...。
申し訳ございません。


よろしくお願いいたします。

**Comment by ys1227** [comment]
ありがとうございます！
